In [1]:
import torch
import torch.nn as nn

In [2]:
rnn = nn.RNN(input_size=3, hidden_size=2, num_layers=2, nonlinearity='relu', bias=False, batch_first=False)
print(rnn.weight_ih_l0.data)
print(rnn.weight_ih_l1.data)
print(rnn.weight_hh_l0.data)
print(rnn.weight_hh_l1.data)

tensor([[ 0.2826, -0.3373,  0.2062],
        [-0.3126, -0.6534, -0.6177]])
tensor([[-0.1035, -0.0665],
        [-0.6990,  0.0839]])
tensor([[ 0.3240,  0.0997],
        [-0.1140, -0.3130]])
tensor([[-0.1855, -0.1067],
        [ 0.5084, -0.3747]])


In [14]:
# Define your RNN
rnn = nn.RNN(input_size=1, hidden_size=2, num_layers=2, nonlinearity='relu', bias=False, batch_first=False)
total_params = sum(p.numel() for p in rnn.parameters())
print(f"Number of parameters in the RNN: {total_params}\n")

# Set the weights for the first layer
rnn.weight_ih_l0.data = torch.tensor([[1.0],[2.0]])
rnn.weight_ih_l1.data = torch.tensor([[1.0, 0.0], [2.0, 1.0]])

rnn.weight_hh_l0.data = torch.tensor([[0.0, 0.0], [0.0, 0.0]])
rnn.weight_hh_l1.data = torch.tensor([[0.0, 0.0], [0.0, 0.0]])

input = torch.arange(1, 3).view(2, 1).float()

h0 = torch.tensor([[0.0, 0.0], [0.0, 0.0]])
output, hn = rnn(input, h0)

# print
print("- state weight:\n", rnn.all_weights[0])
print()
print("- hidden features weight:\n", rnn.all_weights[1])
print()
print("- output:\n", output)
print()
print("- last hidden:\n", hn)

Number of parameters in the RNN: 14

- state weight:
 [Parameter containing:
tensor([[1.],
        [2.]], requires_grad=True), Parameter containing:
tensor([[0., 0.],
        [0., 0.]], requires_grad=True)]

- hidden features weight:
 [Parameter containing:
tensor([[1., 0.],
        [2., 1.]], requires_grad=True), Parameter containing:
tensor([[0., 0.],
        [0., 0.]], requires_grad=True)]

- output:
 tensor([[1., 4.],
        [2., 8.]], grad_fn=<SqueezeBackward1>)

- last hidden:
 tensor([[2., 4.],
        [2., 8.]], grad_fn=<SqueezeBackward1>)
