In [1]:
import torch
import torch.nn as nn

In [50]:
rnn = nn.RNN(input_size=3, hidden_size=2, num_layers=2, nonlinearity='relu', bias=False, batch_first=False)
print(rnn.weight_ih_l0.data)
print(rnn.weight_ih_l1.data)
print(rnn.weight_hh_l0.data)
print(rnn.weight_hh_l1.data)

tensor([[-0.3127,  0.5798,  0.0979],
        [-0.4454, -0.5373, -0.1473]])
tensor([[-0.4811,  0.4856],
        [-0.6226,  0.1770]])
tensor([[-0.4968,  0.0646],
        [ 0.6541, -0.1710]])
tensor([[-0.4524, -0.5419],
        [ 0.6132,  0.0794]])


In [61]:
# Define your RNN
rnn = nn.RNN(input_size=1, hidden_size=2, num_layers=2, nonlinearity='relu', bias=False, batch_first=False)
total_params = sum(p.numel() for p in rnn.parameters())
print(f"Number of parameters in the RNN: {total_params}\n")

# Set the weights for the first layer
rnn.weight_ih_l0.data = torch.tensor([[1.0],[2.0]])
rnn.weight_ih_l1.data = torch.tensor([[1.0, 1.0], [2.0, 1.0]])

rnn.weight_hh_l0.data = torch.tensor([[1.0, 2.0], [1.0, 1.0]])
rnn.weight_hh_l1.data = torch.tensor([[1.0, 1.0], [1.0, 1.0]])

input = torch.arange(1, 5).view(4, 1).float()
output, hn = rnn(input)

# print
print("- state weight:\n", rnn.all_weights[0])
print()
print("- hidden features weight:\n", rnn.all_weights[1])
print()
print("- output:\n", output)
print()
print("- last hidden:\n", hn)

Number of parameters in the RNN: 14

- state weight:
 [Parameter containing:
tensor([[1.],
        [2.]], requires_grad=True), Parameter containing:
tensor([[1., 2.],
        [1., 1.]], requires_grad=True)]

- hidden features weight:
 [Parameter containing:
tensor([[1., 1.],
        [2., 1.]], requires_grad=True), Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)]

- output:
 tensor([[  3.,   4.],
        [ 21.,  28.],
        [ 93., 117.],
        [330., 398.]], grad_fn=<SqueezeBackward1>)

- last hidden:
 tensor([[ 68.,  52.],
        [330., 398.]], grad_fn=<SqueezeBackward1>)
